"""
VOLTIX Internship — Task 3
HR Employee Attrition Analysis

This script:
1. Loads and cleans the HR Employee Attrition dataset.
2. Performs the analyses requested in Task 3.
3. Creates visualizations.
4. Exports a cleaned dataset and summary tables.

Power BI dashboard:
The cleaned CSV generated by this script can be imported into Power BI
to create the required interactive dashboard.
"""

from pathlib import Path
import pandas as pd
import matplotlib.pyplot as plt


# ============================================================
# 1. CONFIGURATION
# ============================================================

BASE_DIR = Path(__file__).resolve().parent
DATASET_PATH = BASE_DIR / "Dataset" / "WA_Fn-UseC_-HR-Employee-Attrition.csv"
OUTPUT_DATASET_PATH = BASE_DIR / "Dataset" / "HR_Employee_Attrition_Cleaned.csv"
CHARTS_DIR = BASE_DIR / "Charts"

CHARTS_DIR.mkdir(parents=True, exist_ok=True)


# ============================================================
# 2. LOAD DATA
# ============================================================

print("=" * 60)
print("HR EMPLOYEE ATTRITION ANALYSIS")
print("=" * 60)

df = pd.read_csv(DATASET_PATH)

print("\n--- DATASET OVERVIEW ---")
print(f"Rows: {df.shape[0]}")
print(f"Columns: {df.shape[1]}")


# ============================================================
# 3. DATA CLEANING
# ============================================================

print("\n--- DATA CLEANING ---")

# Remove duplicated rows.
duplicates = df.duplicated().sum()
print(f"Duplicate rows found: {duplicates}")

df = df.drop_duplicates().copy()

# Check missing values.
missing_values = df.isnull().sum()
print("\nMissing values by column:")
print(missing_values[missing_values > 0])

# Remove columns that contain only one unique value.
constant_columns = [
    column for column in df.columns
    if df[column].nunique(dropna=False) <= 1
]

if constant_columns:
    print(f"\nConstant columns removed: {constant_columns}")
    df = df.drop(columns=constant_columns)

# Convert categorical Yes/No columns to consistent string values.
yes_no_columns = [
    "Attrition",
    "OverTime",
    "Over18",
    "BusinessTravel",
    "Gender",
    "MaritalStatus"
]

for column in yes_no_columns:
    if column in df.columns:
        df[column] = df[column].astype(str).str.strip()

# Ensure numeric columns have numeric types where applicable.
numeric_columns = [
    "Age",
    "DailyRate",
    "DistanceFromHome",
    "Education",
    "EmployeeCount",
    "EmployeeNumber",
    "EnvironmentSatisfaction",
    "HourlyRate",
    "JobInvolvement",
    "JobLevel",
    "JobSatisfaction",
    "MonthlyIncome",
    "MonthlyRate",
    "NumCompaniesWorked",
    "PercentSalaryHike",
    "PerformanceRating",
    "RelationshipSatisfaction",
    "StandardHours",
    "StockOptionLevel",
    "TotalWorkingYears",
    "TrainingTimesLastYear",
    "WorkLifeBalance",
    "YearsAtCompany",
    "YearsInCurrentRole",
    "YearsSinceLastPromotion",
    "YearsWithCurrManager"
]

for column in numeric_columns:
    if column in df.columns:
        df[column] = pd.to_numeric(df[column], errors="coerce")

# Fill numeric missing values with the median if any exist.
for column in df.select_dtypes(include="number").columns:
    if df[column].isnull().any():
        df[column] = df[column].fillna(df[column].median())

# Fill remaining categorical missing values with the mode.
for column in df.select_dtypes(exclude="number").columns:
    if df[column].isnull().any():
        df[column] = df[column].fillna(df[column].mode()[0])

print(f"\nRows after cleaning: {len(df)}")
print(f"Columns after cleaning: {len(df.columns)}")
print(f"Total missing values after cleaning: {df.isnull().sum().sum()}")


# ============================================================
# 4. ATTRITION METRICS
# ============================================================

total_employees = len(df)
attrition_count = (df["Attrition"] == "Yes").sum()
attrition_rate = attrition_count / total_employees * 100
average_salary = df["MonthlyIncome"].mean()
average_experience = df["TotalWorkingYears"].mean()

print("\n--- KEY KPIs ---")
print(f"Total Employees: {total_employees}")
print(f"Employees with Attrition: {attrition_count}")
print(f"Attrition Rate: {attrition_rate:.2f}%")
print(f"Average Monthly Income: {average_salary:.2f}")
print(f"Average Total Working Years: {average_experience:.2f}")


# ============================================================
# 5. ANALYSIS BY DEPARTMENT AND JOB ROLE
# ============================================================

print("\n--- EMPLOYEES BY DEPARTMENT ---")
employees_by_department = (
    df["Department"]
    .value_counts()
    .rename_axis("Department")
    .reset_index(name="Employee_Count")
)
print(employees_by_department)

print("\n--- EMPLOYEES BY JOB ROLE ---")
employees_by_job_role = (
    df["JobRole"]
    .value_counts()
    .rename_axis("JobRole")
    .reset_index(name="Employee_Count")
)
print(employees_by_job_role)


# ============================================================
# 6. SALARY, EXPERIENCE AND PERFORMANCE
# ============================================================

print("\n--- SALARY BY DEPARTMENT ---")
salary_by_department = (
    df.groupby("Department", as_index=False)["MonthlyIncome"]
    .mean()
    .rename(columns={"MonthlyIncome": "Average_Monthly_Income"})
)
print(salary_by_department)

print("\n--- SALARY BY JOB ROLE ---")
salary_by_job_role = (
    df.groupby("JobRole", as_index=False)["MonthlyIncome"]
    .mean()
    .rename(columns={"MonthlyIncome": "Average_Monthly_Income"})
    .sort_values("Average_Monthly_Income", ascending=False)
)
print(salary_by_job_role)

print("\n--- EXPERIENCE AND SALARY ---")
experience_salary = (
    df.groupby("TotalWorkingYears", as_index=False)["MonthlyIncome"]
    .mean()
    .rename(columns={"MonthlyIncome": "Average_Monthly_Income"})
)
print(experience_salary.head())

print("\n--- PERFORMANCE RATING ---")
performance_summary = (
    df["PerformanceRating"]
    .value_counts()
    .sort_index()
    .rename_axis("PerformanceRating")
    .reset_index(name="Employee_Count")
)
print(performance_summary)


# ============================================================
# 7. SATISFACTION ANALYSIS
# ============================================================

print("\n--- JOB SATISFACTION ---")
job_satisfaction = (
    df["JobSatisfaction"]
    .value_counts()
    .sort_index()
    .rename_axis("JobSatisfaction")
    .reset_index(name="Employee_Count")
)
print(job_satisfaction)

print("\n--- WORK-LIFE BALANCE ---")
work_life_balance = (
    df["WorkLifeBalance"]
    .value_counts()
    .sort_index()
    .rename_axis("WorkLifeBalance")
    .reset_index(name="Employee_Count")
)
print(work_life_balance)


# ============================================================
# 8. ATTRITION ANALYSIS
# ============================================================

print("\n--- ATTRITION OVERVIEW ---")
attrition_summary = (
    df["Attrition"]
    .value_counts()
    .rename_axis("Attrition")
    .reset_index(name="Employee_Count")
)
attrition_summary["Percentage"] = (
    attrition_summary["Employee_Count"] / total_employees * 100
)
print(attrition_summary)

print("\n--- ATTRITION BY OVERTIME ---")
attrition_by_overtime = pd.crosstab(
    df["OverTime"],
    df["Attrition"],
    normalize="index"
) * 100
print(attrition_by_overtime)

print("\n--- ATTRITION BY JOB SATISFACTION ---")
attrition_by_job_satisfaction = pd.crosstab(
    df["JobSatisfaction"],
    df["Attrition"],
    normalize="index"
) * 100
print(attrition_by_job_satisfaction)

print("\n--- ATTRITION BY WORK-LIFE BALANCE ---")
attrition_by_work_life = pd.crosstab(
    df["WorkLifeBalance"],
    df["Attrition"],
    normalize="index"
) * 100
print(attrition_by_work_life)

print("\n--- ATTRITION BY DEPARTMENT ---")
attrition_by_department = (
    df.groupby("Department")["Attrition"]
    .apply(lambda x: (x == "Yes").mean() * 100)
    .reset_index(name="Attrition_Rate")
    .sort_values("Attrition_Rate", ascending=False)
)
print(attrition_by_department)

print("\n--- ATTRITION BY JOB ROLE ---")
attrition_by_job_role = (
    df.groupby("JobRole")["Attrition"]
    .apply(lambda x: (x == "Yes").mean() * 100)
    .reset_index(name="Attrition_Rate")
    .sort_values("Attrition_Rate", ascending=False)
)
print(attrition_by_job_role)


# ============================================================
# 9. VISUALIZATIONS
# ============================================================

def save_bar_chart(data, x, y, title, filename, rotation=0):
    plt.figure(figsize=(10, 6))
    plt.bar(data[x].astype(str), data[y])
    plt.title(title)
    plt.xlabel(x)
    plt.ylabel(y)
    plt.xticks(rotation=rotation, ha="right")
    plt.tight_layout()
    plt.savefig(CHARTS_DIR / filename, dpi=150)
    plt.close()


def save_line_chart(data, x, y, title, filename):
    plt.figure(figsize=(10, 6))
    plt.plot(data[x], data[y], marker="o")
    plt.title(title)
    plt.xlabel(x)
    plt.ylabel(y)
    plt.tight_layout()
    plt.savefig(CHARTS_DIR / filename, dpi=150)
    plt.close()


# Employees by department
save_bar_chart(
    employees_by_department,
    "Department",
    "Employee_Count",
    "Employees by Department",
    "employees_by_department.png"
)

# Employees by job role
save_bar_chart(
    employees_by_job_role,
    "JobRole",
    "Employee_Count",
    "Employees by Job Role",
    "employees_by_job_role.png",
    rotation=35
)

# Average salary by department
save_bar_chart(
    salary_by_department,
    "Department",
    "Average_Monthly_Income",
    "Average Monthly Income by Department",
    "salary_by_department.png"
)

# Average salary by job role
save_bar_chart(
    salary_by_job_role,
    "JobRole",
    "Average_Monthly_Income",
    "Average Monthly Income by Job Role",
    "salary_by_job_role.png",
    rotation=35
)

# Salary vs experience
save_line_chart(
    experience_salary,
    "TotalWorkingYears",
    "Average_Monthly_Income",
    "Average Monthly Income by Total Working Years",
    "salary_vs_experience.png"
)

# Performance rating
save_bar_chart(
    performance_summary,
    "PerformanceRating",
    "Employee_Count",
    "Employees by Performance Rating",
    "performance_rating.png"
)

# Job satisfaction
save_bar_chart(
    job_satisfaction,
    "JobSatisfaction",
    "Employee_Count",
    "Employees by Job Satisfaction",
    "job_satisfaction.png"
)

# Work-life balance
save_bar_chart(
    work_life_balance,
    "WorkLifeBalance",
    "Employee_Count",
    "Employees by Work-Life Balance",
    "work_life_balance.png"
)

# Attrition overview
save_bar_chart(
    attrition_summary,
    "Attrition",
    "Employee_Count",
    "Employee Attrition",
    "attrition_overview.png"
)

# Attrition by overtime
overtime_attrition_plot = (
    df.groupby(["OverTime", "Attrition"])
    .size()
    .reset_index(name="Employee_Count")
)
pivot_overtime = overtime_attrition_plot.pivot(
    index="OverTime",
    columns="Attrition",
    values="Employee_Count"
).fillna(0)

pivot_overtime.plot(kind="bar", figsize=(10, 6))
plt.title("Attrition by Overtime")
plt.xlabel("OverTime")
plt.ylabel("Employee Count")
plt.xticks(rotation=0)
plt.tight_layout()
plt.savefig(CHARTS_DIR / "attrition_by_overtime.png", dpi=150)
plt.close()

# Attrition by job satisfaction
job_sat_attrition_plot = (
    df.groupby(["JobSatisfaction", "Attrition"])
    .size()
    .reset_index(name="Employee_Count")
)
pivot_job_sat = job_sat_attrition_plot.pivot(
    index="JobSatisfaction",
    columns="Attrition",
    values="Employee_Count"
).fillna(0)

pivot_job_sat.plot(kind="bar", figsize=(10, 6))
plt.title("Attrition by Job Satisfaction")
plt.xlabel("Job Satisfaction")
plt.ylabel("Employee Count")
plt.xticks(rotation=0)
plt.tight_layout()
plt.savefig(CHARTS_DIR / "attrition_by_job_satisfaction.png", dpi=150)
plt.close()

# Attrition by work-life balance
work_life_attrition_plot = (
    df.groupby(["WorkLifeBalance", "Attrition"])
    .size()
    .reset_index(name="Employee_Count")
)
pivot_work_life = work_life_attrition_plot.pivot(
    index="WorkLifeBalance",
    columns="Attrition",
    values="Employee_Count"
).fillna(0)

pivot_work_life.plot(kind="bar", figsize=(10, 6))
plt.title("Attrition by Work-Life Balance")
plt.xlabel("Work-Life Balance")
plt.ylabel("Employee Count")
plt.xticks(rotation=0)
plt.tight_layout()
plt.savefig(CHARTS_DIR / "attrition_by_work_life_balance.png", dpi=150)
plt.close()

# Attrition by department
save_bar_chart(
    attrition_by_department,
    "Department",
    "Attrition_Rate",
    "Attrition Rate by Department",
    "attrition_by_department.png"
)

# Attrition by job role
save_bar_chart(
    attrition_by_job_role,
    "JobRole",
    "Attrition_Rate",
    "Attrition Rate by Job Role",
    "attrition_by_job_role.png",
    rotation=35
)


# ============================================================
# 10. EXPORT CLEANED DATASET
# ============================================================

df.to_csv(OUTPUT_DATASET_PATH, index=False)

print("\n--- EXPORT ---")
print(f"Cleaned dataset saved to: {OUTPUT_DATASET_PATH}")
print(f"Charts saved to: {CHARTS_DIR}")

print("\nAnalysis completed successfully.")
